image: node:12

stages:
    - dependencies
    - build
    - containerization
    - deploy
    
cache:
    paths:
        - node_modules/

install_dependencies:
    stage: dependencies
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/


# DESARROLLO CAMBIA
containerization:
    stage: containerization # must match the stage name declared above
    script:
        - echo $CI_PROJECT_NAME 
        - docker build -t $CI_PROJECT_NAME .
# -------------

register_image:
    stage: containerization
    variables:
        SHA: $CI_COMMIT_SHORT_SHA
    script:
        - docker tag $CI_PROJECT_NAME $DOCKER_SERVER/$CI_PROJECT_NAME:$SHA
        - docker tag $CI_PROJECT_NAME $DOCKER_SERVER/$CI_PROJECT_NAME:latest
        - docker push $DOCKER_SERVER/$CI_PROJECT_NAME:$SHA
        - docker push $DOCKER_SERVER/$CI_PROJECT_NAME:latest
    only:
        - master

deploy_to_desarrollo:
    stage: deploy
    variables:
        APP_PORT: $APP_PORT
        IMAGE: $CI_PROJECT_NAME:latest
    script: 
        - echo $APP_PORT 
        - docker-compose down 
        - docker-compose up -d --build
    only:
        - desarrollo
    tags: 
        - desarrollo

deploy_to_prod:
    stage: deploy
    variables:
        MYSQL_SERVER: $PROD_MYSQL_SERVER 
        MYSQL_USER: $DESA_MYSQL_USER
        MYSQL_PW: $DESA_MYSQL_PASS
        MYSQL_DB: $DESA_MYSQL_DB
        MYSQL_PORT: $DESA_MYSQL_PORT
        APP_PORT: $APP_PORT
        IMAGE: $DOCKER_SERVER/$CI_PROJECT_NAME:latest
    script: 
        - echo $IMAGE 
        - docker pull $DOCKER_SERVER/$CI_PROJECT_NAME:latest
        - docker-compose down 
        - docker-compose up -d
    only:
        - master
    when: manual
    tags: 
        - master
